### ISSUE TITLE
Gomstreamer Failed last night

### ISSUE THREAD

**Issue by venport** [sjp/GOMstreamer#1]
Hey Thanks for the great tool, I was able to capture the stream the other night, however that was in test SQtest quality, however I changed it to HQ last night and it failed. I do have a premium account with GOM and I did not get an authentication error so I don;t expect it to be an account issue. 

I'll leave my input below to see if that helps you out any. Tonight I'll try and run 2 instances of the gomstreamer one on SQtest and another on HQ to see how that performs and give you an update.

Thanks again

Carl-

./delayed-save.sh 
Stream URL: http://38.108.112.126:8902/view.cgi?hid=1&cid=20806&nid=902&uno=2567500&uip=98.238.165.254&title=2nd+Generation+Intel(R)+Core(TM)+GSL+Mar.+Code+A&key=7e50924177815c24fc736d31d94c7024

VLC command: vlc "http://38.108.112.126:8902/view.cgi?hid=1&cid=20806&nid=902&uno=2567500&uip=98.238.165.254&title=2nd+Generation+Intel(R)+Core(TM)+GSL+Mar.+Code+A&key=7e50924177815c24fc736d31d94c7024" "--http-caching=30000" --demux=dump --demuxdump-file="gsl20110309.mp4" vlc://quit

Waiting until 18:00 KST for recording to begin.
This will occur after the following wait: 7h 0m 48s

Dumping stream via VLC...
VLC media player 1.1.4 The Luggage (revision exported)
Blocked: call to unsetenv("DBUS_ACTIVATION_ADDRESS")
Blocked: call to unsetenv("DBUS_ACTIVATION_BUS_TYPE")
[0x810d914] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Blocked: call to setlocale(6, "")
Blocked: call to sigaction(17, 0xb73d10d4, 0xb73d1048)
Warning: call to signal(13, 0x1)
Warning: call to signal(13, 0x1)
Warning: call to srand(1299841353)
Warning: call to rand()
Blocked: call to setlocale(6, "")

(process:24279): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
Warning: call to signal(13, 0x1)
Warning: call to signal(13, 0x1)
Blocked: call to setenv("_PX_CONFIG_ORDER", "", 1)
[0x843989c] access_http access error: failed to read answer
[0x843989c] access_http access error: failed to read answer
[0x843989c] access_mms access error: failed to read answer
[0x81b95ec] main input error: open of `http://38.108.112.126:8902/view.cgi?hid=1&cid=20806&nid=902&uno=2567500&uip=98.238.165.254&title=2nd+Generation+Intel(R)+Core(TM)+GSL+Mar.+Code+A&key=7e50924177815c24fc736d31d94c7024' failed: (null)

**Comment by sjp** [comment]
I am aware of the issue and I think it lies in the fact that because the delay is so long, the URL link expires.

I'll be fixing this shortly to be able to delay first, then sign in and grab the stream URL and play it. This will probably fix the issue.

**Comment by venport** [comment]
Is it the delay between when I started the script and when the stream started? 

I'll try a cron job tonight so start not long before the stream starts, that should be an ok work around. Thanks for all the work you do with this.

Carl-

**Comment by sjp** [comment]
Yeah the delay between when you executed the script (which then grabbed the stream URL) and when the stream went live is the problem.

I think the delay needs to be lower than some arbitrary length of time, not sure what that is though.
