### ISSUE TITLE
Neither release or latest from master appears to work anymore.

### ISSUE THREAD

**Issue by bhelyer** [sjp/GOMstreamer#15]
In the case of the former,

`ERROR Unable to find the gomcmd URL in the GOX XML file.`

is the ultimate error and for the latter it just says 

`Playing stream...`

Then immediately exits. Saving the stream has similar results in both cases.

Platform is Linux, FWIW

**Comment by bhelyer** [comment]
I got it to work by enabling logging and running the command generated by hand. It doesn't work otherwise.

**Comment by sjp** [comment]
The latest commit on the master branch should work.

Let me know if there are any problems, I'll be pushing out a new release soon if there are no problems.

**Comment by bhelyer** [comment]
Yep, that fixed it. Thanks!
