### ISSUE TITLE
Cache stream xml

### ISSUE THREAD

**Issue by willth** [sjp/GOMstreamer#18]
Either the site was getting hammered or technical issues but for whatever reason gomtv was not responsive for a while tonight.

Keeping copies of stream xmls so fetching a new one isn't required would be one fix. Then something like --xml=~/gomstreamer/xmlcache/20120131-1.xml could be done.

**Comment by sjp** [comment]
Caching can certainly be applied but I'm not entirely sure whether it's warranted yet.

I did toy with caching about a year ago and ran into some problems but I think the GOMtv streaming system is sufficiently different now to have another go at it.

**Comment by Cronium** [comment]
I'm not sure if its gom servers being hammered, but it seems very common for gomstreamer to hang while trying to either pull the "Live" page or otherwise the XML file. For example its hung right now, while gomplayer works fine.
