### ISSUE TITLE
"Both Streams" option doesn't work?

### ISSUE THREAD

**Issue by Cronium** [sjp/GOMstreamer#19]
As far as I can tell the .net version of GomStreamer, it only appears to download the second stream.

**Comment by sjp** [comment]
Yeah, I noticed this too. This is fixed locally. I'll be pushing the changes out a couple of hours prior to the next airing of the GSL.

**Comment by sjp** [comment]
This is now fixed, please try the latest version:

https://github.com/sjp/GOMstreamer.NET/commit/c50f5894a7ff287c88cf99f370b2220fed6ce15e
