### ISSUE TITLE
gomstreamer.py

### ISSUE THREAD

**Issue by coryo** [sjp/GOMstreamer#2]
145: cmd = cmd + " --verbose 2"
147: cmd = cmd + " --verbose 0"
154: cmd = cmd + " --http-user-agent KPeerClient"

need to change that to --verbose=2, --verbose=0, --http-user-agent=KPeerClient

**Comment by sjp** [comment]
I think they would've worked regardless, but I've amended the additions to make it more consistent.

Thanks.

**Comment by coryo** [comment]
on OSX it would treat "0" as another file to add to the playlist with the space in there.

**Comment by sjp** [comment]
Ah I see. On Linux the behaviour appears to be different.

Unfortunately I don't have OSX to test with. Duly noted for future changes.

Thanks again :).
