### ISSUE TITLE
Make "Play" load VLC with dump.ogm

### ISSUE THREAD

**Issue by Cronium** [sjp/GOMstreamer#20]
Bit of a simple suggestion, but I think we won't get piping to VLC working any time soon, that "Play" should simply save the dump.ogm somewhere like a /tmp or Local Files\Temporary Internet Files then simply play it with VLC. Would save a couple of clicks.

**Comment by sjp** [comment]
Yeah, agreed. I'll probably try to work that in this evening before pushing out a new release.

I think a delay of something like 10 seconds before loading VLC should give us a large enough buffer.

**Comment by sjp** [comment]
This has been implemented.

https://github.com/sjp/GOMstreamer.NET/commit/c50f5894a7ff287c88cf99f370b2220fed6ce15e

I've decided to simply make it the same as a 'Save' mode, but with VLC automatically loading the stream as it's being saved.
