### ISSUE TITLE
fix the season

### ISSUE THREAD

**Issue by gtmanfred** [sjp/GOMstreamer#23]
They just moved to season8 for up and down matches so I had to over ride it this morning.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
http://sjp.co.nz/projects/gomstreamer/season.txt <-- here 

:-D

**Comment by sjp** [comment]
Thanks. What should the season URL be now? I had no problems grabbing the stream using the default methods.

**Comment by gtmanfred** [comment]
hmmm... Now that you mention it, I think i read the code wrong and was using that method as well, I will try it again today and see if it gets fixed
