### ISSUE TITLE
VLC sometimes fails to play the stream

### ISSUE THREAD

**Issue by DIDI2002** [sjp/GOMstreamer#24]
Hi, 
I'm using gomstreamer on Archlinux with my gomtv Premium account. 
When I start the stream, about 50% of tries VLC gets stuck spamming:  

[h264 @ 0x7fbab4c2fce0] Cannot (re-)initialize context during parallel decoding.
[h264 @ 0x7f2f30c9c020] decode_slice_header error 
[h264 @ 0x7f2f30c9c020] non-existing PPS 0 referenced 
[h264 @ 0x7f2f30c9c020] decode_slice_header error 
[h264 @ 0x7f2f30c9c920] no frame!  

Sometimes it starts after a few seconds, sometimes it doesn't. 
I'm using Arch's VLC 2.0.1-1, wget 1.13.4-1, gomstreamer from current git.  

Any pointers?

**Comment by sjp** [comment]
I think this occurs when we start piping the stream to VLC and there isn't yet enough data to show a video stream.

Initially it's probably going to do this a few times. I think the issue will disappear once wget is (reliably) grabbing the stream for a short time.

Does this output prevent the stream from playing or is it simply spewing a lot of text to the console while VLC plays the stream?

**Comment by DIDI2002** [comment]
Yes, this prevents the stream from playing. Maybe it depends on the first piece of data vlc receives (keyframe or something in between). Seems to behave really random.

Current VLC-git doesn't change anything either.

**Comment by sjp** [comment]
Hmmmm, does the audio continue playing? I've had instances myself where the video doesn't appear for a while but the audio is not a problem.

This was not the case for me prior to 2.x.x, for you too?

**Comment by DIDI2002** [comment]
Audio is working, but the video does not show up even after a few minutes.
I'll try again with Code S tomorrow and see if I can pipe to mplayer instead.

**Comment by sjp** [comment]
Ah yes, I'm pretty sure this is a VLC issue.

Will have a look later, and perhaps write a bug report for a regression going from 1.x to 2.x

**Comment by DIDI2002** [comment]
Cool, thanks for the great work with gomstreamer!

**Comment by sjp** [comment]
I've just noticed something that reliably works around the issue for me is dragging the slider to the start of the video.

From then I can just watch as per usual, no blank video output.

**Comment by drin** [comment]
This is so pro. sjp you are kick ass. <3

also I had this same problem, so glad this thread was easy to find.

**Comment by dstructcode** [comment]
I'm not sure if anyone still has this problem, but I had it on OSX 10.8.2 with VLC 2.0.3.  Essentially what happens is nothing when you first start the script.  It brings up the playlist and you have to click play on fd://0.  After that, only audio starts and even waiting a few minutes no video starts.  I was able to get the video to start playing shortly after starting the stream by going to Video -> Video Track -> disable and then Video -> Video Track -> Track 1.  After that the video popped up and took about 10-15 seconds to buffer and then smooth sailing from then on in.  Hope this helps someone else out!
