### ISSUE TITLE
SQTest is not working 

### ISSUE THREAD

**Issue by gtmanfred** [sjp/GOMstreamer#25]
WARNING Unable to use SQTest quality stream.
WARNING Purchase a premium ticket for access to this stream quality.
WARNING Trying SQTest quality instead.

**Comment by sjp** [comment]
While this may be an issue on GOMtv's end, does the issue still present itself as of the latest commit? 54c9c99ec76bf9e0c9d36d6fa87caf8545e21216

**Comment by gtmanfred** [comment]
I jumped the gun, It was that the stream hadn't actually started yet I think

**Comment by sjp** [comment]
Ah ok. Closing.
