### ISSUE TITLE
Account authorization on scheduled play should occur before "waiting until"

### ISSUE THREAD

**Issue by joequery** [sjp/GOMstreamer#28]
In the interest of failing failing fast, a user with incorrect authorization shouldn't be met with a "This will occur after waiting X amount of time". The login credentials should be checked first. They might be waiting for GSL in the background to come up but it never would.

**Comment by sjp** [comment]
Good point. I think in the past this was intentional because they messed with authentication a bit.

I think it's safe now to try breaking faster rather than after a delay.

**Comment by sjp** [comment]
I've made it so that we check that authentication is successful prior to delaying in a95959792ac4a259393b2b2055055afc6210bb8e.

We still sign in again later as part of our stream URL generation process, because it avoids some potential issues, but I think this works well enough.

**Comment by joequery** [comment]
Not sure if you know this, but you can reference issues in commits by adding "Closes #x" where x is the issue number. So if in that commit you had the message as "Now checking sign in prior to delaying the stream. Closes #28", this issue would be closed. It's pretty handy :)

**Comment by sjp** [comment]
I knew about it but thanks anyway :). I thought I'd let you have a look before closing the issue just in case you had something to add.

**Comment by joequery** [comment]
Ah, well thanks for that :)
