### ISSUE TITLE
VLC closes after I hit play with SQtest Stream

### ISSUE THREAD

**Issue by uKioops** [sjp/GOMstreamer#30]
Hi,

Gomstreamer never worked for me at the moment, everytime I try to launch the Stream, VLC opens and closes instantly... I've searched google and this forum to find an answer but without success. So I try here now.

I have win7, VLC 2.0.3

Thanks if you have anything on that :)

**Comment by sjp** [comment]
Are you using the C# client (i.e. the release with a `GOMstreamer.exe`) or the Python client?

**Comment by uKioops** [comment]
It's GOMstreamer.exe

When I hit Go!, the wget.exe starts "http request sent, awaiting response...." VLC starts, and both window close

**Comment by NumbPlumb** [comment]
Is there any solution for this? I'm currently having the exact same problem but only when I attempt to watch the stream in HQ (I have a pass)
