### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by kollektiv** [sjp/GOMstreamer#5]
I'm using OSX 10.6, VLC 1.1.9, and Python 2.6.1. Below is the error when I run play.command using 0.6.3. I then tried the latest version from master and I got the same error.

<pre>
Signing in.
Grabbing the 'Live' page.
Parsing the 'Live' page for the GOX XML link.
Grabbing the GOX XML file.
Parsing the GOX XML file for the stream URL.
Parsing for the HTTP stream.
Stream found, cleaning up URL.

Stream URL: http://38.108.112.168:8902/view.cgi?...

Command: curl -A KPeerClient "http://38.108.112.168:8902/view.cgi?..." -o "-" | /A
pplications/VLC.app/Contents/MacOS/VLC - --file-caching 30000 vlc://quit

Playing stream...
dyld: Library not loaded: @loader_path/lib/libvlc.5.dylib
  Referenced from: /Applications/VLC.app/Contents/MacOS/VLC
  Reason: image not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21590    0 21590    0     0   119k      0 --:--:-- --:--:-- --:--:--  135k
curl: (23) Failed writing body (0 != 5792)
sh: line 1: 28797 Done(23)                curl -A KPeerClient "http://38.108.112.168:8902/view.cgi?..." -o "-"
     28798 Trace/BPT trap          | /Applications/VLC.app/Contents/MacOS/VLC - --file-caching 30000 vlc://quit
</pre>

**Comment by sjp** [comment]
I don't have OSX so I can't be sure about this, but it seems to me that there's something with VLC that's now breaking.

Is VLC able to be run correctly from the command line by typing `vlc`? The VLC path that GOMstreamer looks for is `/Applications/VLC.app/Contents/MacOS/VLC`, is VLC still located here?

**Comment by kollektiv** [comment]
I reinstalled VLC and now it's working correctly on command line. However I get a different error shown below.

<pre>
Playing stream...
[0x100214d18] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
102  2766    0  2766    0     0  11233      0 --:--:-- --:--:-- --:--:-- 13109libdvdnav: Using dvdnav version 4.1.4
libdvdread: Using libdvdcss version 1.2.10 for DVD access
libdvdread: Can't stat /Users/tyen/dev/GOMstreamer/30000
No such file or directory
libdvdread: Could not open /Users/tyen/dev/GOMstreamer/30000
libdvdnav: vm: failed to open/read the DVD
</pre>

**Comment by fj128** [comment]
Can you take the command the GOMStreamer issues, swap "`-`" and "`--file-caching 30000`" arguments like this:

```
curl -A KPeerClient "http://38.108.112.168:8902/view.cgi?..." -o "-" | /Applications/VLC.app/Contents/MacOS/VLC --file-caching 30000 - vlc://quit
```

... and see if it works then? Like, just copy, modify and run what it says after `Command:`". It even should work when no broadcast is active, like right now, they serve some kind of two-seconds intro clip or something.

By the looks of it (in particular, by seeing vlc trying to open `/Users/tyen/dev/GOMstreamer/30000`) something is wrong with the way vlc parses command-line arguments on OS X. Or maybe something is wrong everywhere else, since the vlc documentation says "`Usage: vlc [options] [stream] ...`"

**Comment by sjp** [comment]
Closing due to lack of follow-up. If this issue still persists, send me a message and I'll open it up again.
