### ISSUE TITLE
Boxer vs Yellow, wtf did they do?

### ISSUE THREAD

**Issue by fj128** [sjp/GOMstreamer#7]
Now when you click "go live" they send you to a page with a single javascript, uh, script, redirecting you to the right page.

Quick workaround: 

```
# gomtvLiveURL = getLivePageURL(gomtvURL)
gomtvLiveURL = 'http://www.gomtv.net/event/LimJinRok_Live.gom'
```

I wonder if this is a one-time thing, or I should add some kind of heuristic to detect stunts like that...

By the way, HQ is free for this event!

**Comment by Fiaxhs** [comment]
Hmm, not working for me, stream url is like http:///view.cgi?blublublu

I guess there's something I'm missing :)

Edit : ok, when setting quality to SQ or HQ it's now working.

**Comment by fj128** [comment]
Seems like their stuff is glitching fiercely, sometimes it works for me and sometimes it doesn't (both here and in the GOM player). Though not like what you describe: half of the time the GOX link doesn't has `mb_no=0`, like, this is a valid link and then an invalid link:

```
http://www.gomtv.net/gox/gox.gom?leagueid=0&strLevel=HQ&target=freeLive&mb_no=5bc038623e901420&title=Lim+Jin+Rok+Returns+%3A+StarCraft+2+Superstar+Challenge

http://www.gomtv.net/gox/gox.gom?leagueid=0&strLevel=HQ&target=freeLive&mb_no=0&title=Lim+Jin+Rok+Returns+%3A+StarCraft+2+Superstar+Challenge
```

Then when the script tries to get the actual stream URL their XML service returns 1001 instead (whatever that might mean). It's random, like, I can get 0 several times in a row, then a valid id several times in a row, both in the script and on their page (which involves refreshing it).

**Comment by sjp** [comment]
Hmmm, perhaps what I could do to avoid this situation in future is to get GOMstreamer to grab a txt file from my server.

This txt file could be empty (in the case of no event) or contain the URL to an upcoming event. This would mean we would have a simple method of catching events and we could do this prior to checking the "Go Live" button for the URL.

fj128: Do you think this is a viable solution? Also, I think the 1001 indicates that you are not currently logged in as the JS on the event page says:

``` javascript
if(data == 1001) {
    showLoginBox();
}
```

Not sure why this is appearing though because you should be logged in...

**Comment by fj128** [comment]
> This txt file could be empty (in the case of no event) or contain the URL to an upcoming event. This would mean we would have a simple method of catching events and we could do this prior to checking the "Go Live" button for the URL.

I think it would be better to just extend the current logic (try to get the URL by parsing stuff, fall back on your file in case of any exceptions) onto the entire stream URL retrieval process. It's the way it is now because I thought that if we managed to download the live page then we've used the right address and there's no reason to retry with another in case of any further errors, turns out that it's not necessarily true.

> Also, I think the 1001 indicates that you are not currently logged in

Yeah, that was the problem as I understand it: they failed to generate the authentication token on that page now and then, the "mb_no" thing, both for the script and for the actual people (or rather, the actual browsers).

**Comment by sjp** [comment]
I agree, extending the current logic is probably the best way of approaching the problem. I guess I wasn't thinking properly about the problem earlier. You're right, just the text file that I've got on my server should be sufficient. I just need to update it more frequently...

I'll have a go at this when I've got a bit more time to devote to the issue.

**Comment by sjp** [comment]
Given that we had another live event recently that GOMstreamer broke on, I had a stab at this.

I'll be pushing the changes soon (and probably releasing it as a new version). Essentially the approach I'm taking now is that whenever we grab the page that's pointed to by the 'Go Live' button we inspect the size of the resulting page. If the page is less than 200 characters (an arbitrary number that is small, but large enough to work) we then parse for a relative URL. The relative URL is the real live page that we continue processing as per usual.

Another small fix is that now when there's an event like this, the SQTest stream usually isn't available, so for now I'm assuming that SQTest should become SQ.

**Comment by sjp** [comment]
Latest release covers cases when special events are available on regular streams.
