### ISSUE TITLE
GOMtv updated their website

### ISSUE THREAD

**Issue by sjp** [sjp/GOMstreamer#8]
GOMstreamer does not parse the HTML correctly anymore as it has changed.

A quick example of this is that `live.gom` is now `goLive.gom`.

Will require fixing some of the regexes when scraping but the process should remain roughly the same.

**Comment by mockra** [comment]
Doesn't seem to be working correctly, assuming they changed it again. Thanks for your hard work.

**Comment by sjp** [comment]
Looks like it's due to authentication. Patching ASAP.

**Comment by jasperavisser** [comment]
Gotta say I love how quickly you pick this up. Kudos!

**Comment by sjp** [comment]
It seems the issue lies in the fact that we now authenticate to the following URL: `https://ssl.gomtv.net/userinfo/loginProcess.gom`. This sets cookies for the `gomtv.net` domain.

I can't seem to get the authentication going though. Can't work out the problem yet. I can send the login data, but get no Cookie response.

**Comment by chrippa** [comment]
Hello, this small patch seems to fix it for me.

```
diff --git a/gomstreamer.py b/gomstreamer.py
index aaa7286..6dfecac 100644
--- a/gomstreamer.py
+++ b/gomstreamer.py
@@ -130,7 +130,8 @@ def main():
         delay(options.kt)

     gomtvURL = 'http://www.gomtv.net'
-    gomtvSignInURL = urljoin(gomtvURL, '/user/loginProcess.gom')
+    gomtvSignInURL = 'https://ssl.gomtv.net/userinfo/loginProcess.gom'
+    headers = {'Referer': 'http://www.gomtv.net/'}
     values = {
              'cmd': 'login',
              'rememberme': '1',
@@ -144,7 +145,7 @@ def main():

     # Signing into GOMTV
     print "Signing in."
-    request = urllib2.Request(gomtvSignInURL, data)
+    request = urllib2.Request(gomtvSignInURL, data, headers)
     urllib2.install_opener(opener)
     response = urllib2.urlopen(request)
```

**Comment by sjp** [comment]
Ah, thanks, I knew it would be something simple I was missing. Thanks.

EDIT: Now committed and working fine. Thanks chrippa.
